<?php
/**
 * Created by PhpStorm.
 * User: morningjack
 * Date: 2017/5/24
 * Time: 下午11:15
 */

namespace app\lib\exception;


use Exception;
use think\exception\Handle;
use think\Log;
use think\Request;

class ExceptionHandler extends Handle
{
    private $code;
    private $msg;
    private $errorCode;

    //需要返回客户端当前请求懂得url路径

    public function render(Exception $e)
    {
        //return parent::render($e); // TODO: Change the autogenerated stub
        if ($e instanceof BaseException) {
            //如果是自定义的异常 用户导致的异常，输入，查询
            $this->code = $e->code;
            $this->msg = $e->msg;
            $this->errorCode = $e->errorCode;
        } else {
            if (config('app_debug')) {//Config::get('app_debug')
                //return default error page
                return parent::render($e);
            } else {
                //系统异常
                $this->code = 500;
                $this->msg = '服务器内部错误,不告诉你';
                $this->errorCode = 999;
                //记录日志
                $this->recoredErrorLog($e);
            }
        }
        $request = Request::instance();
        $result = [
            'msg' => $this->msg,
            'error_code' => $this->errorCode,
            'request_url' => $request->url()
        ];
        return json($result, $this->code);
    }

    private function recoredErrorLog(Exception $e)
    {
        //写入日志需要在config开启
        Log::init([
            'type' => 'File',
            'path' => LOG_PATH,
            'level' => ['error']
        ]);
        Log::record($e->getMessage(), $this->code);
    }
}